import { Box } from '@mui/material'
import Head from 'next/head'
import BoxWrapper from '../components/BoxWrapper'
import Provider from '../context/Provider'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <Provider>
      <div className={styles.container}>
        <Head>
          <title>Teste front-end - Mobiauto</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Tabela Fipe
          </h1>

          <p className={styles.description}>
            Consulte o valor de um veículo de forma gratuita
          </p>
          <Box sx={{ minWidth: '40%' }}>
            <BoxWrapper />
          </Box>
        </main>
      </div>
    </Provider>
  )
}
